services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: planner
      POSTGRES_PASSWORD: plannerpw
      POSTGRES_DB: plannerdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./
    command: npm run dev
    environment:
      PORT: 4000
      DATABASE_URL: postgresql://planner:plannerpw@db:5432/plannerdb
      CHOKIDAR_USEPOLLING: "1"
      CHOKIDAR_INTERVAL: "300"
    ports: ["4000:4000"]
    volumes:
      - ./src
      - ./node_modules

volumes:
  pg_data:
